### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/altinn2-convert#4]
We should update this tool to use .NET 6 and latest C# instead of 3.1.

https://github.com/Altinn/altinn2-convert/blob/master/Altinn2Convert.csproj#L5

**Comment by ivarne** [comment]
Why? This will live for only 3 years (if you make the altinn 2 deadline), and is bound to run on windows because of CabLib. We already get warnings (and crashes) because CabLib is old.

**Comment by altinnadmin** [comment]
> Why? 

.NET 3.1 is unsupported in a year, and will not get security-patches.
We shouldn't require app devs to have unsupported software installed on their machines.

Also, why not? It probably does not take many minutes to do.

**Comment by ivarne** [comment]
Sorry, I didn't consider the option of not finishing converting everything in a year. Seems that at least development on this tool should finished by that timeframe. Maybe that is not realistic?

**Comment by altinnadmin** [comment]
The tool should and could be finished well within a year, converting everything for every service owner in that timeframe is a much bigger challenge.

**Comment by ivarne** [comment]
Yea, there will be lots of manual cleanup after this tool has done its job. The list of special cases is just too long (I think),

One solution to the CabLib problem would be to do a preprocessing step that extracts the `.xsn` files from infopath (and deletes `.dll` files that might contain api secrets) so that the final conversion only needs to read `.zip` files. That would work very well if we manage to get the packages directly from the TUL database. I have a draft for a azure function app that takes all packages from a blob container and does this, but I don't get CabLib to work.

**Comment by altinnadmin** [comment]
> there will be lots of manual cleanup

Yup, the tool can automate the most boring/repetitive and time consuming tasks (generating and "wiring up" layouts, data models and texts into a running app), but converting the business logic from C#/XPath must still be done manually.

> One solution to the CabLib problem would be to do a preprocessing step

Yeah, that should be possible

**Comment by ivarne** [comment]
Another reason for not updating is microsofts love for hardcoding version in multiple places in a way that requires pretty deep understanding to figure out why (only) some of my breakpoints suddenly doesn't work.

![image](https://user-images.githubusercontent.com/131616/144225937-99cd3c7e-f126-49d1-a129-9a10d871ff3e.png)

This change definitely took more than "a few minutes". But update to net5.0 was required in order to reference 
![image](https://user-images.githubusercontent.com/131616/144226409-958d1b6c-bf45-483d-83e2-a10398b61b89.png)

**Comment by altinnadmin** [comment]
Heh, nice, but as you know, .NET 5 will soon not be good enough... :) https://github.com/Altinn/altinn-studio/issues/7219

**Comment by ivarne** [comment]
Let's hope I remember this little quirk when you update to 6 😄 and there still are no issues running CabLib.

I tried to create an azure function that extracted xsn files and renamed from GUID to `{{ServiceOwnerCode}}/{{ServiceName}}` when moving between storage containers, but I did not get CabLib to work (on dotnet 4.7). Currently I try to spend more time on translating more and more features, but checkbox is hard because of datamodel inconcistency.

**Comment by altinnadmin** [comment]
> But update to net5.0 was required in order to reference...

Is this something you can create a PR for so we're on the same codebase?

**Comment by ivarne** [comment]
Are you actually working on this? I just assumed the relevance would mainly be for finished functionality, not half finished broken steps between.

**Comment by altinnadmin** [comment]
Nah, if it's WIP and half-broken it's better to wait :)

**Comment by ivarne** [comment]
Half finished - fully broken.

**Comment by altinnadmin** [comment]
Now running on .NET 6
